<?php

namespace App\Filament\Resources;

use App\Filament\Resources\UserResource\Pages;
use App\Models\User;
use Auth;
use Filament\Forms\Components\MultiSelect;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Model;
use STS\FilamentImpersonate\Impersonate;

class UserResource extends Resource
{
    protected static ?string $model = User::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';
    protected static ?string $navigationGroup = 'User Management';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                         MultiSelect::make('roles')->relationship('roles', 'name')
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name'),
                Tables\Columns\TextColumn::make('email'),
                Tables\Columns\TagsColumn::make('roles.name'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Impersonate::make('impersonate'),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function can(string $action, ?Model $record = null): bool
    {
        return Auth::user()->can('user_access'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return Auth::user()->can('user_update'); // TODO: Change the autogenerated stub
    }
    public static function canCreate(): bool
    {
        return Auth::user()->can('user_create'); // TODO: Change the autogenerated stub
    }
    public static function canDelete(Model $record): bool
    {
        return Auth::user()->can('user_delete'); // TODO: Change the autogenerated stub
    }
    public static function canView(Model $record): bool
    {
        return Auth::user()->can('user_read'); // TODO: Change the autogenerated stub
    }
    public static function canDeleteAny(): bool
    {
        return Auth::user()->can('user_delete'); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListUsers::route('/'),
            'create' => Pages\CreateUser::route('/create'),
            'edit' => Pages\EditUser::route('/{record}/edit'),
        ];
    }
}
